CREATE DATABASE FORMULA_UNO_2023
GO
USE FORMULA_UNO_2023
GO

CREATE TABLE ESCUDERIAS(
	idEscuderia int,
	nombreEscuderia varchar(50) NOT NULL,
	CONSTRAINT PK_ESCUDERIAS PRIMARY KEY (idEscuderia)
)

CREATE TABLE PAISES(
	idPais int,
	nombrePais varchar(50) NOT NULL,
	CONSTRAINT PK_PAISES PRIMARY KEY (idPais)
)

CREATE TABLE COMPETIDORES(
	numero int,
	nombre varchar(50) NOT NULL,
	pais int NOT NULL,
	escuderia int NOT NULL,
	fecha date NOT NULL,
	CONSTRAINT PK_COMPETIDORES PRIMARY KEY (numero),
	CONSTRAINT FK_COMPETIDORES_ESCUDERIAS FOREIGN KEY (escuderia)
	REFERENCES ESCUDERIAS (idEscuderia),
	CONSTRAINT FK_COMPETIDORES_PAISES FOREIGN KEY (pais)
	REFERENCES PAISES (idPais)
)